<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document PUBLIC "+//IDN docutils.sourceforge.net//DTD Docutils Generic//EN//XML" "http://docutils.sourceforge.net/docs/ref/docutils.dtd">
<!-- Generated by Docutils 0.13.1 -->
<document source="/home/fbaumanis/openstack/soc8_test/openstack_repo/cinder/doc/source/contributor/api/cinder.volume.drivers.vmware.exceptions.rst">
    <section ids="module-cinder.volume.drivers.vmware.exceptions the-cinder-volume-drivers-vmware-exceptions-module" names="the\ cinder.volume.drivers.vmware.exceptions\ module">
        <title>The <reference internal="True" refid="module-cinder.volume.drivers.vmware.exceptions" reftitle="cinder.volume.drivers.vmware.exceptions"><literal classes="xref py py-mod">cinder.volume.drivers.vmware.exceptions</literal></reference> Module</title>
        <index entries="['single',\ 'cinder.volume.drivers.vmware.exceptions\ (module)',\ 'module-cinder.volume.drivers.vmware.exceptions',\ '',\ None]"></index>
        <paragraph>Exception definitions.</paragraph>
        <index entries="['single',\ 'ClusterNotFoundException',\ 'cinder.volume.drivers.vmware.exceptions.ClusterNotFoundException',\ '',\ None]"></index>
        <desc desctype="exception" domain="py" noindex="False" objtype="exception">
            <desc_signature class="" first="False" fullname="ClusterNotFoundException" ids="cinder.volume.drivers.vmware.exceptions.ClusterNotFoundException" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.ClusterNotFoundException"><desc_annotation xml:space="preserve">exception </desc_annotation><desc_name xml:space="preserve">ClusterNotFoundException</desc_name><desc_parameterlist xml:space="preserve"><desc_parameter xml:space="preserve">message=None</desc_parameter><desc_parameter xml:space="preserve">details=None</desc_parameter><desc_parameter xml:space="preserve">**kwargs</desc_parameter></desc_parameterlist></desc_signature>
            <desc_content>
                <paragraph>Bases: <literal classes="xref py py-class">oslo_vmware.exceptions.VMwareDriverException</literal></paragraph>
                <paragraph>Thrown when the given cluster cannot be found.</paragraph>
                <index entries="['single',\ 'msg_fmt\ (ClusterNotFoundException\ attribute)',\ 'cinder.volume.drivers.vmware.exceptions.ClusterNotFoundException.msg_fmt',\ '',\ None]"></index>
                <desc desctype="attribute" domain="py" noindex="False" objtype="attribute">
                    <desc_signature class="ClusterNotFoundException" first="False" fullname="ClusterNotFoundException.msg_fmt" ids="cinder.volume.drivers.vmware.exceptions.ClusterNotFoundException.msg_fmt" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.ClusterNotFoundException.msg_fmt"><desc_name xml:space="preserve">msg_fmt</desc_name><desc_annotation xml:space="preserve"> = 'Compute cluster: %(cluster)s not found.'</desc_annotation></desc_signature>
                    <desc_content>
                    </desc_content>
                </desc>
            </desc_content>
        </desc>
        <index entries="['single',\ 'InvalidAdapterTypeException',\ 'cinder.volume.drivers.vmware.exceptions.InvalidAdapterTypeException',\ '',\ None]"></index>
        <desc desctype="exception" domain="py" noindex="False" objtype="exception">
            <desc_signature class="" first="False" fullname="InvalidAdapterTypeException" ids="cinder.volume.drivers.vmware.exceptions.InvalidAdapterTypeException" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.InvalidAdapterTypeException"><desc_annotation xml:space="preserve">exception </desc_annotation><desc_name xml:space="preserve">InvalidAdapterTypeException</desc_name><desc_parameterlist xml:space="preserve"><desc_parameter xml:space="preserve">message=None</desc_parameter><desc_parameter xml:space="preserve">details=None</desc_parameter><desc_parameter xml:space="preserve">**kwargs</desc_parameter></desc_parameterlist></desc_signature>
            <desc_content>
                <paragraph>Bases: <literal classes="xref py py-class">oslo_vmware.exceptions.VMwareDriverException</literal></paragraph>
                <paragraph>Thrown when the disk adapter type is invalid.</paragraph>
                <index entries="['single',\ 'msg_fmt\ (InvalidAdapterTypeException\ attribute)',\ 'cinder.volume.drivers.vmware.exceptions.InvalidAdapterTypeException.msg_fmt',\ '',\ None]"></index>
                <desc desctype="attribute" domain="py" noindex="False" objtype="attribute">
                    <desc_signature class="InvalidAdapterTypeException" first="False" fullname="InvalidAdapterTypeException.msg_fmt" ids="cinder.volume.drivers.vmware.exceptions.InvalidAdapterTypeException.msg_fmt" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.InvalidAdapterTypeException.msg_fmt"><desc_name xml:space="preserve">msg_fmt</desc_name><desc_annotation xml:space="preserve"> = 'Invalid disk adapter type: %(invalid_type)s.'</desc_annotation></desc_signature>
                    <desc_content>
                    </desc_content>
                </desc>
            </desc_content>
        </desc>
        <index entries="['single',\ 'InvalidDiskTypeException',\ 'cinder.volume.drivers.vmware.exceptions.InvalidDiskTypeException',\ '',\ None]"></index>
        <desc desctype="exception" domain="py" noindex="False" objtype="exception">
            <desc_signature class="" first="False" fullname="InvalidDiskTypeException" ids="cinder.volume.drivers.vmware.exceptions.InvalidDiskTypeException" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.InvalidDiskTypeException"><desc_annotation xml:space="preserve">exception </desc_annotation><desc_name xml:space="preserve">InvalidDiskTypeException</desc_name><desc_parameterlist xml:space="preserve"><desc_parameter xml:space="preserve">message=None</desc_parameter><desc_parameter xml:space="preserve">details=None</desc_parameter><desc_parameter xml:space="preserve">**kwargs</desc_parameter></desc_parameterlist></desc_signature>
            <desc_content>
                <paragraph>Bases: <literal classes="xref py py-class">oslo_vmware.exceptions.VMwareDriverException</literal></paragraph>
                <paragraph>Thrown when the disk type is invalid.</paragraph>
                <index entries="['single',\ 'msg_fmt\ (InvalidDiskTypeException\ attribute)',\ 'cinder.volume.drivers.vmware.exceptions.InvalidDiskTypeException.msg_fmt',\ '',\ None]"></index>
                <desc desctype="attribute" domain="py" noindex="False" objtype="attribute">
                    <desc_signature class="InvalidDiskTypeException" first="False" fullname="InvalidDiskTypeException.msg_fmt" ids="cinder.volume.drivers.vmware.exceptions.InvalidDiskTypeException.msg_fmt" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.InvalidDiskTypeException.msg_fmt"><desc_name xml:space="preserve">msg_fmt</desc_name><desc_annotation xml:space="preserve"> = 'Invalid disk type: %(disk_type)s.'</desc_annotation></desc_signature>
                    <desc_content>
                    </desc_content>
                </desc>
            </desc_content>
        </desc>
        <index entries="['single',\ 'NoValidDatastoreException',\ 'cinder.volume.drivers.vmware.exceptions.NoValidDatastoreException',\ '',\ None]"></index>
        <desc desctype="exception" domain="py" noindex="False" objtype="exception">
            <desc_signature class="" first="False" fullname="NoValidDatastoreException" ids="cinder.volume.drivers.vmware.exceptions.NoValidDatastoreException" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.NoValidDatastoreException"><desc_annotation xml:space="preserve">exception </desc_annotation><desc_name xml:space="preserve">NoValidDatastoreException</desc_name><desc_parameterlist xml:space="preserve"><desc_parameter xml:space="preserve">message=None</desc_parameter><desc_parameter xml:space="preserve">details=None</desc_parameter><desc_parameter xml:space="preserve">**kwargs</desc_parameter></desc_parameterlist></desc_signature>
            <desc_content>
                <paragraph>Bases: <literal classes="xref py py-class">oslo_vmware.exceptions.VMwareDriverException</literal></paragraph>
                <paragraph>Thrown when there are no valid datastores.</paragraph>
                <index entries="['single',\ 'msg_fmt\ (NoValidDatastoreException\ attribute)',\ 'cinder.volume.drivers.vmware.exceptions.NoValidDatastoreException.msg_fmt',\ '',\ None]"></index>
                <desc desctype="attribute" domain="py" noindex="False" objtype="attribute">
                    <desc_signature class="NoValidDatastoreException" first="False" fullname="NoValidDatastoreException.msg_fmt" ids="cinder.volume.drivers.vmware.exceptions.NoValidDatastoreException.msg_fmt" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.NoValidDatastoreException.msg_fmt"><desc_name xml:space="preserve">msg_fmt</desc_name><desc_annotation xml:space="preserve"> = 'There are no valid datastores.'</desc_annotation></desc_signature>
                    <desc_content>
                    </desc_content>
                </desc>
            </desc_content>
        </desc>
        <index entries="['single',\ 'NoValidHostException',\ 'cinder.volume.drivers.vmware.exceptions.NoValidHostException',\ '',\ None]"></index>
        <desc desctype="exception" domain="py" noindex="False" objtype="exception">
            <desc_signature class="" first="False" fullname="NoValidHostException" ids="cinder.volume.drivers.vmware.exceptions.NoValidHostException" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.NoValidHostException"><desc_annotation xml:space="preserve">exception </desc_annotation><desc_name xml:space="preserve">NoValidHostException</desc_name><desc_parameterlist xml:space="preserve"><desc_parameter xml:space="preserve">message=None</desc_parameter><desc_parameter xml:space="preserve">details=None</desc_parameter><desc_parameter xml:space="preserve">**kwargs</desc_parameter></desc_parameterlist></desc_signature>
            <desc_content>
                <paragraph>Bases: <literal classes="xref py py-class">oslo_vmware.exceptions.VMwareDriverException</literal></paragraph>
                <paragraph>Thrown when there are no valid ESX hosts.</paragraph>
                <index entries="['single',\ 'msg_fmt\ (NoValidHostException\ attribute)',\ 'cinder.volume.drivers.vmware.exceptions.NoValidHostException.msg_fmt',\ '',\ None]"></index>
                <desc desctype="attribute" domain="py" noindex="False" objtype="attribute">
                    <desc_signature class="NoValidHostException" first="False" fullname="NoValidHostException.msg_fmt" ids="cinder.volume.drivers.vmware.exceptions.NoValidHostException.msg_fmt" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.NoValidHostException.msg_fmt"><desc_name xml:space="preserve">msg_fmt</desc_name><desc_annotation xml:space="preserve"> = 'There are no valid ESX hosts.'</desc_annotation></desc_signature>
                    <desc_content>
                    </desc_content>
                </desc>
            </desc_content>
        </desc>
        <index entries="['single',\ 'ProfileNotFoundException',\ 'cinder.volume.drivers.vmware.exceptions.ProfileNotFoundException',\ '',\ None]"></index>
        <desc desctype="exception" domain="py" noindex="False" objtype="exception">
            <desc_signature class="" first="False" fullname="ProfileNotFoundException" ids="cinder.volume.drivers.vmware.exceptions.ProfileNotFoundException" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.ProfileNotFoundException"><desc_annotation xml:space="preserve">exception </desc_annotation><desc_name xml:space="preserve">ProfileNotFoundException</desc_name><desc_parameterlist xml:space="preserve"><desc_parameter xml:space="preserve">message=None</desc_parameter><desc_parameter xml:space="preserve">details=None</desc_parameter><desc_parameter xml:space="preserve">**kwargs</desc_parameter></desc_parameterlist></desc_signature>
            <desc_content>
                <paragraph>Bases: <literal classes="xref py py-class">oslo_vmware.exceptions.VMwareDriverException</literal></paragraph>
                <paragraph>Thrown when the given storage profile cannot be found.</paragraph>
                <index entries="['single',\ 'msg_fmt\ (ProfileNotFoundException\ attribute)',\ 'cinder.volume.drivers.vmware.exceptions.ProfileNotFoundException.msg_fmt',\ '',\ None]"></index>
                <desc desctype="attribute" domain="py" noindex="False" objtype="attribute">
                    <desc_signature class="ProfileNotFoundException" first="False" fullname="ProfileNotFoundException.msg_fmt" ids="cinder.volume.drivers.vmware.exceptions.ProfileNotFoundException.msg_fmt" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.ProfileNotFoundException.msg_fmt"><desc_name xml:space="preserve">msg_fmt</desc_name><desc_annotation xml:space="preserve"> = 'Storage profile: %(storage_profile)s not found.'</desc_annotation></desc_signature>
                    <desc_content>
                    </desc_content>
                </desc>
            </desc_content>
        </desc>
        <index entries="['single',\ 'VirtualDiskNotFoundException',\ 'cinder.volume.drivers.vmware.exceptions.VirtualDiskNotFoundException',\ '',\ None]"></index>
        <desc desctype="exception" domain="py" noindex="False" objtype="exception">
            <desc_signature class="" first="False" fullname="VirtualDiskNotFoundException" ids="cinder.volume.drivers.vmware.exceptions.VirtualDiskNotFoundException" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.VirtualDiskNotFoundException"><desc_annotation xml:space="preserve">exception </desc_annotation><desc_name xml:space="preserve">VirtualDiskNotFoundException</desc_name><desc_parameterlist xml:space="preserve"><desc_parameter xml:space="preserve">message=None</desc_parameter><desc_parameter xml:space="preserve">details=None</desc_parameter><desc_parameter xml:space="preserve">**kwargs</desc_parameter></desc_parameterlist></desc_signature>
            <desc_content>
                <paragraph>Bases: <literal classes="xref py py-class">oslo_vmware.exceptions.VMwareDriverException</literal></paragraph>
                <paragraph>Thrown when virtual disk is not found.</paragraph>
                <index entries="['single',\ 'msg_fmt\ (VirtualDiskNotFoundException\ attribute)',\ 'cinder.volume.drivers.vmware.exceptions.VirtualDiskNotFoundException.msg_fmt',\ '',\ None]"></index>
                <desc desctype="attribute" domain="py" noindex="False" objtype="attribute">
                    <desc_signature class="VirtualDiskNotFoundException" first="False" fullname="VirtualDiskNotFoundException.msg_fmt" ids="cinder.volume.drivers.vmware.exceptions.VirtualDiskNotFoundException.msg_fmt" module="cinder.volume.drivers.vmware.exceptions" names="cinder.volume.drivers.vmware.exceptions.VirtualDiskNotFoundException.msg_fmt"><desc_name xml:space="preserve">msg_fmt</desc_name><desc_annotation xml:space="preserve"> = 'There is no virtual disk device.'</desc_annotation></desc_signature>
                    <desc_content>
                    </desc_content>
                </desc>
            </desc_content>
        </desc>
    </section>
</document>
